/*
 * Public API Surface of router
 */

export { default as invariant } from 'tiny-invariant';
export { default as warning } from 'tiny-warning';

export {
  TSR_DEFERRED_PROMISE,
  cleanPath,
  createControlledPromise,
  decode,
  deepEqual,
  defaultParseSearch,
  defaultSerializeError,
  defaultStringifySearch,
  defer,
  encode,
  escapeJSON,
  functionalUpdate,
  interpolatePath,
  isMatch,
  isPlainArray,
  isPlainObject,
  joinPaths,
  matchByPath,
  matchPathname,
  parsePathname,
  parseSearchWith, // SSR
  pick,
  removeBasepath,
  replaceEqualDeep,
  resolvePath,
  retainSearchParams,
  rootRouteId,
  shallow,
  stringifySearchWith,
  stripSearchParams,
  trimPath,
  trimPathLeft,
  trimPathRight,
} from '@tanstack/router-core';

export type {
  AbsoluteToPath,
  ActiveOptions,
  AllContext,
  AllLoaderData,
  AllParams,
  AnyContext,
  AnyPathParams,
  AnyRedirect,
  AnyRoute,
  AnyRouteMatch,
  AnyRouteWithContext,
  AnyRouter,
  AnyRouterWithContext,
  AnySchema,
  AnyValidator,
  AnyValidatorAdapter,
  AnyValidatorFn,
  AnyValidatorObj,
  Assign,
  BaseRouteOptions,
  BeforeLoadContextOptions,
  BeforeLoadContextParameter,
  BeforeLoadFn,
  BuildLocationFn,
  BuildNextOptions,
  CommitLocationOptions,
  Constrain,
  ContextAsyncReturnType,
  ContextOptions,
  ContextReturnType,
  ControllablePromise,
  ControlledPromise,
  DefaultValidator,
  DeferredPromise,
  DeferredPromiseState,
  ErrorComponentProps,
  ErrorRouteProps,
  Expand,
  ExtractedEntry,
  ExtractedPromise,
  ExtractedStream,
  FileBaseRouteOptions,
  FileRouteTypes,
  FileRoutesByPath,
  FullSearchSchema,
  FullSearchSchemaInput,
  FullSearchSchemaOption,
  InferAllContext,
  InferAllParams,
  InferDescendantToPaths,
  InferFullSearchSchema,
  InferFullSearchSchemaInput,
  InjectedHtmlEntry,
  IntersectAssign,
  LazyRouteOptions,
  LinkOptions,
  ListenerFn,
  LoaderFnContext,
  LooseAsyncReturnType,
  LooseReturnType,
  MakeOptionalPathParams,
  MakeRemountDepsOptionsUnion,
  MakeRouteMatch,
  MakeRouteMatchUnion,
  Manifest,
  MatchLocation,
  MatchRouteOptions,
  MergeAll,
  MetaDescriptor,
  NavigateFn,
  NavigateOptions,
  NotFoundRouteProps,
  ParamsOptions,
  ParseParamsFn,
  ParsePathParams,
  ParseRoute,
  ParseSplatParams,
  ParsedLocation,
  PathParamOptions,
  PreloadableObj,
  Redirect,
  Register,
  RegisteredRouter,
  RelativeToCurrentPath,
  RelativeToParentPath,
  RelativeToPath,
  RelativeToPathAutoComplete,
  RemountDepsOptions,
  RemoveLeadingSlashes,
  RemoveTrailingSlashes,
  ResolveAllContext,
  ResolveAllParamsFromParent,
  ResolveFullPath,
  ResolveFullSearchSchema,
  ResolveFullSearchSchemaInput,
  ResolveId,
  ResolveLoaderData,
  ResolveParams,
  ResolveRelativePath,
  ResolveRoute,
  ResolveRouteContext,
  ResolveSearchValidatorInput,
  ResolveSearchValidatorInputFn,
  ResolveValidatorInput,
  ResolveValidatorInputFn,
  ResolveValidatorOutput,
  ResolveValidatorOutputFn,
  ResolvedRedirect,
  RootRouteId,
  RootRouteOptions,
  RouteById,
  RouteByPath,
  RouteConstraints,
  RouteContext,
  RouteContextFn,
  RouteContextOptions,
  RouteContextParameter,
  RouteIds,
  RouteLinkEntry,
  RouteLoaderFn,
  RouteMask,
  RouteMatch,
  RouteOptions,
  RoutePathOptions,
  RoutePathOptionsIntersection,
  RoutePaths,
  RouterConstructorOptions,
  RouterContextOptions,
  RouterErrorSerializer,
  RouterEvent,
  RouterEvents,
  RouterListener,
  RouterManagedTag,
  RouterOptions,
  RouterState,
  RoutesById,
  RoutesByPath,
  SearchFilter,
  SearchParamOptions,
  SearchParser,
  SearchSchemaInput,
  SearchSerializer,
  Segment,
  Serializable,
  SerializerParse,
  SerializerParseBy,
  SerializerStringify,
  SerializerStringifyBy,
  SplatParams,
  StartSerializer,
  StaticDataRouteOption,
  StreamState,
  StringifyParamsFn,
  ToMaskOptions,
  ToOptions,
  ToPathOption,
  ToSubOptions,
  TrailingSlashOption,
  TrimPath,
  TrimPathLeft,
  TrimPathRight,
  UpdatableRouteOptions,
  UpdatableStaticRouteOption,
  UseNavigateResult,
  Validator,
  ValidatorAdapter,
  ValidatorFn,
  ValidatorObj,
} from '@tanstack/router-core';

export {
  createBrowserHistory,
  createHashHistory,
  createHistory,
  createMemoryHistory,
} from '@tanstack/history';

export type {
  BlockerFn,
  HistoryLocation,
  HistoryState,
  ParsedPath,
  RouterHistory,
} from '@tanstack/history';

export { createRouter } from './lib/create-router';

export {
  PathParamError,
  SearchParamError,
  componentTypes,
  getInitialRouterState,
  lazyFn,
} from '@tanstack/router-core';

export { isNotFound, notFound } from '@tanstack/router-core';
export type { NotFoundError } from '@tanstack/router-core';

export type {
  InferFrom,
  InferMaskFrom,
  InferMaskTo,
  InferSelected,
  InferShouldThrow,
  InferStrict,
  InferTo,
  ValidateFromPath,
  ValidateId,
  ValidateNavigateOptions,
  ValidateNavigateOptionsArray,
  ValidateParams,
  ValidateRedirectOptions,
  ValidateRedirectOptionsArray,
  ValidateSearch,
  ValidateToPath,
  ValidateUseParamsResult,
  ValidateUseSearchResult,
} from '@tanstack/router-core';

export * from './lib/file-route';
export * from './lib/link';
export * from './lib/outlet';
export * from './lib/route';
export * from './lib/router';
export * from './lib/router-context';
export * from './lib/router-devtools';
